### PR TITLE
Fix Vector::axpy for noncommutative cases

### PR DESCRIPTION
**Pull request by kubkon**
One example would be performing simple matrix multiplication
over a division algebra such as quaternions.

---
This change is [Reviewable](https://reviewable.io/reviews/rustsim/nalgebra/648)

### CODE REVIEW

**Comment by kubkon** [comment]
cc @sebcrozet

**Comment by sebcrozet** [comment]
Hi! Sorry for the late answer and thank you for this PR!

I don't believe modifying `axpy` that way is correct. The `axpy` operation should do `y = a * x + beta * y`. With your change it becomes `y = x * a + y * beta` which does not match the definition.

I think the actual problem that breaks non-commutative operations is our current implementation of `gemv` which includes the operation `alpha * v[j] * m[i, j]` instead of `alpha * m[i, j] * v[j]` (i.e. with `v[j]` on the rightmost place). Though it seems like performing the operations the correct way would prevent us from writing `gemv` in term of `axpy`. Perhaps we need an (private) operator, say, `axcpy(a, x, c, y, beta)` that does `a * x * c + beta * y` and would be used like that in `gemv`:

```rust
self.axcpy(alpha, &col2, val, N::one());
```

Also, `self.axpy(a, x, beta)` would simply be equal to `self.axcpy(a, x, N::one(), beta)`.

I'm afraid this may cause some performance regression though so we should see what impact this has on our benchmarks.

**Comment by kubkon** [comment]
Hi @sebcrozet! Thanks for your reply and apologies for not tending to this earlier but got properly swamped by other projects and just didn't find the time to look at this in more detail.

Anyhow, I've had a stab at addressing your comment and added `Vector::axcpy` method as described by you. I've also replaced `array_axpy` and `array_ax` with `array_axcpy` and `array_axc` respectively which much like `Vector::axcpy` preserve the order of scalar multiplication. Let me know if that's what you've had in mind.

As far as the benchmarks are concerned, if you were to explain how to benchmark the crate, I'd be happy to look at it and report back my findings.

**Comment by sebcrozet** [comment]
Hi @kubkon!
No problem. Thank you for working on this issue again!
In order to run the benchmarks you need to use the nightly compiler and:

1. Checkout the repository to a state that does not include your change.
2. Un-comment the [criterion](https://github.com/rustsim/nalgebra/blob/dev/Cargo.toml#L63) dependency on the `Cargo.toml`.
3. Run `cargo bench` a couple of times.

Then, checkout the repository to the head of your working branch, un-comment criterion again, and run `cargo bench` again, **once** (it is important that it is run only once here). During this run, criterion will tell you how the performances were affected by your change. You can paste in this issue the output of criterion for this run.

What criterion does is that it compares the execution times between the current run of `cargo bench` and the previous one.

**Comment by kubkon** [comment]
Here's the summary of benchmarking the changes:
* 20 regressions
* 75 improvements
* 14 no change

I'm gonna skip printing out the improvements and no-changers, and will focus on regressions instead. Also, you can find the full output [here](https://gist.github.com/kubkon/25bd98764f7365ba12b0c58795d0a0d8).

```
  Benchmarking mat4_add_m                                                                                                                                                                               
  mat4_add_m              time:   [8.5291 ns 8.5611 ns 8.5994 ns]                                                      
                          change: [+5.7318% +6.3671% +7.0148%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 9 outliers among 100 measurements (9.00%)                                                                      
    9 (9.00%) high severe

  Benchmarking mat100_add_mat100                                                                                                                                                                 
  mat100_add_mat100       time:   [4.4864 us 4.4929 us 4.5001 us]                                                      
                          change: [+3.8096% +4.0596% +4.3143%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 4 outliers among 100 measurements (4.00%)                                                                      
    2 (2.00%) high mild                                                                                                
    2 (2.00%) high severe 

  Benchmarking mat7_mul_mat7                                                                                                                                                                     
  mat7_mul_mat7           time:   [191.11 ns 191.31 ns 191.54 ns]                                                      
                          change: [+8.4738% +8.7424% +9.0274%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 18 outliers among 100 measurements (18.00%)                                                                    
    17 (17.00%) high mild                                                                                              
    1 (1.00%) high severe

  Benchmarking mat9_mul_mat9                                                                                                                                                                         
  mat9_mul_mat9           time:   [308.53 ns 308.75 ns 308.99 ns]                                                      
                          change: [+2.5651% +2.7603% +2.9536%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 2 outliers among 100 measurements (2.00%)                                                                      
    2 (2.00%) high mild

  Benchmarking mat10_mul_mat10_static                                                                                                                                                    
  mat10_mul_mat10_static  time:   [203.38 ns 203.54 ns 203.71 ns]                                                      
                          change: [+28.512% +28.771% +29.018%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 10 outliers among 100 measurements (10.00%)                                                                    
    7 (7.00%) low mild                                                                                                 
    2 (2.00%) high mild                                                                                                
    1 (1.00%) high severe

  Benchmarking vec10000_axpy_beta_f32                                                                                                                                                      
  vec10000_axpy_beta_f32  time:   [1.2433 us 1.2448 us 1.2463 us]                                                      
                          change: [+3.2944% +3.5543% +3.7824%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 7 outliers among 100 measurements (7.00%)                                                                      
    6 (6.00%) high mild                                                                                                
    1 (1.00%) high severe

  Benchmarking quaternion_inv                                                                                                                                                                  
  quaternion_inv          time:   [8.1163 ns 8.1248 ns 8.1341 ns]                                                      
                          change: [+2.3485% +2.7346% +3.0748%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 4 outliers among 100 measurements (4.00%)                                                                      
    3 (3.00%) high mild                                                                                                
    1 (1.00%) high severe

  Benchmarking bidiagonalize_unpack_500x100                                                                                                                                          
  bidiagonalize_unpack_500x100                                                                                         
                          time:   [3.2879 ms 3.2899 ms 3.2920 ms]                                                      
                          change: [+2.3342% +2.5011% +2.6642%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 5 outliers among 100 measurements (5.00%)                                                                      
    1 (1.00%) low mild                                                                                                 
    1 (1.00%) high mild                                                                                                
    3 (3.00%) high severe

  Benchmarking cholesky_inverse_500x500                                                                                                                                                 
  cholesky_inverse_500x500                                                                                             
                          time:   [32.486 ms 32.500 ms 32.516 ms]                                                      
                          change: [+1.8750% +2.0032% +2.1207%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 12 outliers among 100 measurements (12.00%)                                                                    
    2 (2.00%) low mild                                                                                                 
    7 (7.00%) high mild                                                                                                
    3 (3.00%) high severe

  Benchmarking full_piv_lu_inverse_10x10                                                                                                                                               
  full_piv_lu_inverse_10x10                                                                                            
                          time:   [1.1363 us 1.1390 us 1.1425 us]                                                      
                          change: [+4.0041% +4.6598% +5.3238%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 2 outliers among 100 measurements (2.00%)                                                                      
    2 (2.00%) high mild

  Benchmarking hessenberg_decompose_unpack_200x200                                                                                                                     
  hessenberg_decompose_unpack_200x200                                                                                  
                          time:   [4.2654 ms 4.2698 ms 4.2756 ms]                                                      
                          change: [+2.4078% +2.5561% +2.7128%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 7 outliers among 100 measurements (7.00%)                                                                      
    5 (5.00%) high mild                                                                                                
    2 (2.00%) high severe


```  Benchmarking lu_decompose_10x10                                                                                                                                                        
  lu_decompose_10x10      time:   [399.05 ns 399.39 ns 399.77 ns]                                                      
                          change: [+5.5828% +5.7866% +6.0024%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 6 outliers among 100 measurements (6.00%)                                                                      
    3 (3.00%) high mild                                                                                                
    3 (3.00%) high severe

  Benchmarking lu_inverse_10x10                                                                                                                                                         
  lu_inverse_10x10        time:   [1.1878 us 1.1896 us 1.1916 us]                                                      
                          change: [+3.8273% +4.0843% +4.3339%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 9 outliers among 100 measurements (9.00%)                                                                      
    9 (9.00%) high mild

  Benchmarking qr_decompose_unpack_100x100                                                                                                                                         
  qr_decompose_unpack_100x100                                                                                          
                          time:   [361.59 us 362.34 us 363.24 us]                                                      
                          change: [+2.6485% +2.9670% +3.2997%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 5 outliers among 100 measurements (5.00%)                                                                      
    3 (3.00%) high mild                                                                                                
    2 (2.00%) high severe  

  Benchmarking qr_decompose_unpack_500x100                                                                                                                                      
  qr_decompose_unpack_500x100                                                                                          
                          time:   [2.0331 ms 2.0342 ms 2.0354 ms]                                                      
                          change: [+4.6465% +4.8736% +5.0960%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 6 outliers among 100 measurements (6.00%)                                                                      
    4 (4.00%) high mild                                                                                                
    2 (2.00%) high severe                                                                                              
                                                                                                                       
  Benchmarking qr_solve_10x10                                                                                                                                       
  qr_solve_10x10          time:   [207.23 ns 207.37 ns 207.52 ns]                                                      
                          change: [+2.1648% +2.3690% +2.5701%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 3 outliers among 100 measurements (3.00%)                                                                      
    1 (1.00%) high mild                                                                                                
    2 (2.00%) high severe                                                                                              
                                                                                                                       
  Benchmarking qr_solve_100x100                                                                                                                                              
  qr_solve_100x100        time:   [4.7540 us 4.7818 us 4.8122 us]                                                      
                          change: [+4.3857% +4.8337% +5.3132%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 17 outliers among 100 measurements (17.00%)                                                                    
    5 (5.00%) high mild                                                                                                
    12 (12.00%) high severe                                                                                            
                                                                                                                       
  Benchmarking qr_inverse_10x10                                                                                        
  qr_inverse_10x10        time:   [1.3987 us 1.3997 us 1.4008 us]                                                      
                          change: [+2.1959% +2.5216% +2.8187%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 6 outliers among 100 measurements (6.00%)                                                                      
    4 (4.00%) high mild                                                                                                
    2 (2.00%) high severe                                                                                              
                                                                                                                       
  Benchmarking qr_inverse_100x100                                                                                                                                                    
  qr_inverse_100x100      time:   [441.42 us 442.68 us 444.79 us]                                                      
                          change: [+4.8073% +5.0538% +5.3182%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 7 outliers among 100 measurements (7.00%)                                                                      
    1 (1.00%) low mild                                                                                                 
    2 (2.00%) high mild                                                                                                
    4 (4.00%) high severe

  Benchmarking symmetric_eigen_decompose_200x200                                                                                                                               
  symmetric_eigen_decompose_200x200                                                                                    
                          time:   [10.839 ms 10.862 ms 10.892 ms]                                                      
                          change: [+1.1140% +1.2388% +1.3720%] (p = 0.00 < 0.05)                                       
                          Performance has regressed.                                                                   
  Found 9 outliers among 100 measurements (9.00%)                                                                      
    4 (4.00%) high mild                                                                                                
    5 (5.00%) high severe

**Comment by kubkon** [comment]
Ping @sebcrozet

**Comment by sebcrozet** [comment]
Think you for the ping @kubkon.
The reported regressions and improvements seems to bee low enough, so chances are they are mostly noise.

More investigations will be done next year when we will focus more on performance. In the mean time let's merge this so we have a correct result.

Thanks!

**Comment by kubkon** [comment]
> Think you for the ping @kubkon.
> The reported regressions and improvements seems to bee low enough, so chances are they are mostly noise.
> 
> More investigations will be done next year when we will focus more on performance. In the mean time let's merge this so we have a correct result.
> 
> Thanks!

My pleasure! Glad we can merge this in :-)

**Pull request merged**
